name = "ajd-fyi"
main = "src/index.ts"
compatibility_date = "2025-02-14"
observability = { enabled = true }

vars = { DOMAIN = "ajd.fyi" }
kv_namespaces = [{ binding = "URLS", id = "ac9274e00fda4038aeebf9531ca5d69b" }]
routes = [{ pattern = "ajd.fyi", custom_domain = true }]
