name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'tests/**'
      - 'README.md'

jobs:
  lint:
    # The type of runner that the job will run on
    name: Eslint
    runs-on: 'ubuntu-latest'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.tool-versions'
          cache: npm
      - run: npm ci
      - run: npm run lint

  test:
    # The type of runner that the job will run on
    runs-on: 'ubuntu-latest'
    name: Vitest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.tool-versions'
          cache: npm
      - run: npm ci
      - run: npm run test

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
